services:
  database:
    image: carlosmz87/pf_inventario_database:latest
    container_name: pf_inventario_database_container
    volumes:
      - pf_inventario_data:/var/lib/mysql
    networks:
      - pf_inventario_network  
    ports:
      - "3306:${DATABASE_PORT}"
    env_file:
      - .env.prod
  backend:
    image: carlosmz87/pf_inventario_backend:latest
    container_name: pf_inventario_backend_container
    ports:
      - "3000:${BACKEND_PORT}"
    volumes:
      - ${RUTA_FOTOS}:/app/uploads
    networks:
      - pf_inventario_network 
    env_file:
      - .env.prod
    depends_on:
      - database
    restart: on-failure
    healthcheck:
      test: curl --fail http://10.50.59.151:3000/api/db-check || exit 1 
      interval: 20m
      timeout: 30m
      retries: 5
      start_period: 30m
  frontend:
    image: carlosmz87/pf_inventario_frontend:latest
    container_name: pf_inventario_frontend_container
    ports:
      - "80:${FRONTEND_PORT}"
    depends_on:
      - backend
    restart: always
    networks:
      - pf_inventario_network     
    env_file:
      - .env.prod
  prometheus:
    image: prom/prometheus:latest
    container_name: pf_inventario_prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Volumen para tu configuración personalizada de Prometheus
    networks:
      - pf_inventario_network
    restart: always
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: pf_inventario_grafana_container
    ports:
      - "8080:3000"
    volumes:
      - pf_inventario_monitoring_grafana:/var/lib/grafana
      - ./monitoring/grafana/Dashboards/metrics.json:/var/lib/grafana/provisioning/dashboards/metrics.json
      - ./monitoring/grafana/provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    env_file:
      - .env.prod
    networks:
      - pf_inventario_network
    restart: always
    depends_on:
      - prometheus
volumes:
  pf_inventario_data:
  pf_inventario_monitoring_grafana:

networks:
  pf_inventario_network:

  
