USE `Inventario`;
INSERT INTO cat_editorial (descripcion) VALUES ('BPB Publications');
INSERT INTO cat_editorial (descripcion) VALUES ('Kathryn Gollin Marshak');
INSERT INTO cat_editorial (descripcion) VALUES ('Osborne McGraw-Hill');
INSERT INTO cat_editorial (descripcion) VALUES ('Fondo Educativo Interamericano, S.A.');
INSERT INTO cat_editorial (descripcion) VALUES ('Alfaomega Grupo Editor');
INSERT INTO cat_editorial (descripcion) VALUES ('Prentice Hall');
INSERT INTO cat_editorial (descripcion) VALUES ('Limusa');
INSERT INTO cat_editorial (descripcion) VALUES ('Pearson Educacion');
INSERT INTO cat_editorial (descripcion) VALUES ('Prentice Hal Inc');
INSERT INTO cat_editorial (descripcion) VALUES ('Addison-Wesley Iberoamericana');
INSERT INTO cat_editorial (descripcion) VALUES ('CECSA');
INSERT INTO cat_editorial (descripcion) VALUES ('Thomson Learning');
INSERT INTO cat_editorial (descripcion) VALUES ('Thomson');
INSERT INTO cat_editorial (descripcion) VALUES ('SINTESIS');
INSERT INTO cat_editorial (descripcion) VALUES ('Trillas');
INSERT INTO cat_editorial (descripcion) VALUES ('Internal Business Machines Corporation');
INSERT INTO cat_editorial (descripcion) VALUES ('International Thomson Editores');
INSERT INTO cat_editorial (descripcion) VALUES ('Paraninfo ');
INSERT INTO cat_editorial (descripcion) VALUES ('John Wiley & Sons');
INSERT INTO cat_editorial (descripcion) VALUES ('Oracle ');
INSERT INTO cat_editorial (descripcion) VALUES ('Anzos');
INSERT INTO cat_editorial (descripcion) VALUES ('Wiley');
INSERT INTO cat_editorial (descripcion) VALUES ('Compañia Editorial Continental');
INSERT INTO cat_editorial (descripcion) VALUES ('Blume');
INSERT INTO cat_editorial (descripcion) VALUES ('Tata');
INSERT INTO cat_editorial (descripcion) VALUES ('IBM');
INSERT INTO cat_editorial (descripcion) VALUES ('DOSSAT');
INSERT INTO cat_editorial (descripcion) VALUES ('O''REILLY');
INSERT INTO cat_editorial (descripcion) VALUES ('Microsoft ');
INSERT INTO cat_editorial (descripcion) VALUES ('ESRI Press');
INSERT INTO cat_editorial (descripcion) VALUES ('Techmedia');
INSERT INTO cat_editorial (descripcion) VALUES ('x');
INSERT INTO cat_editorial (descripcion) VALUES ('Tech Publications');
INSERT INTO cat_editorial (descripcion) VALUES ('URL Guatemala');
INSERT INTO cat_editorial (descripcion) VALUES ('North-Holland Publishing Company');
INSERT INTO cat_editorial (descripcion) VALUES ('PHI Editorial');
INSERT INTO cat_editorial (descripcion) VALUES ('Fawcett Columbine');
INSERT INTO cat_editorial (descripcion) VALUES ('Diana');
INSERT INTO cat_editorial (descripcion) VALUES ('Super Aprendizaje');
INSERT INTO cat_editorial (descripcion) VALUES ('Plaza & Janes');
INSERT INTO cat_editorial (descripcion) VALUES ('Science Research Associates');
INSERT INTO cat_editorial (descripcion) VALUES ('Representaciones y Servicios');
INSERT INTO cat_editorial (descripcion) VALUES ('Academic Press');
INSERT INTO cat_editorial (descripcion) VALUES ('Public Diplomacy Division');
INSERT INTO cat_editorial (descripcion) VALUES ('Macrobit Editores S.A.');
INSERT INTO cat_editorial (descripcion) VALUES ('Harcourt Brace Jovanovich');
INSERT INTO cat_editorial (descripcion) VALUES ('Improved System Echnologies');
INSERT INTO cat_editorial (descripcion) VALUES ('The Gideons International');
INSERT INTO cat_editorial (descripcion) VALUES ('Ra-Ma');
INSERT INTO cat_editorial (descripcion) VALUES ('IEEE Computer Society');
INSERT INTO cat_editorial (descripcion) VALUES ('Longseller');
INSERT INTO cat_editorial (descripcion) VALUES ('USAC');