USE `Inventario`;
INSERT INTO `ubicacion_salon` (`descripcion`) VALUES ('LABORATORIO DE LA INDIA 1'), ('LABORATORIO DE LA INDIA 2'), ('LABORATORIO DE LA INDIA 3'), ('LABORATORIO ECYS 013'), ('LABORATORIO ECYS 014'), ('OFICINA'), ('OTRO');

